version: "3.9"

services:
  db:
    image: postgres:15
    container_name: api-financeira-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-financeira-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-financeira
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: Host=db;Port=5432;Username=user;Password=password;Database=finance_db
    depends_on:
      - db
    networks:
      - api-financeira-network

networks:
  api-financeira-network:
    driver: bridge